
services:

  tailscale:
    image: tailscale/tailscale:stable
    restart: unless-stopped
    network_mode: service:openconnect
    environment:
      TS_EXTRA_ARGS: --login-server=${TAILSCALE_SERVER} --advertise-routes=${TAILSCALE_ROUTES}
      TS_HOSTNAME: ${TAILSCALE_HOSTNAME}
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TS_STATE_DIR: "/var/lib/tailscale"
    volumes:
      - ${VOLUME_PATH}tailscale:/var/lib/tailscale
    depends_on:
      - openconnect

  openconnect:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      GATEWAY: ${GATEWAY}
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
      OTP_SECRET: ${OTP_SECRET}


